//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lists
    {
        public Lists()
        {
            this.ListItems = new HashSet<ListItems>();
        }
    
        public int ListID { get; set; }
        public string ListName { get; set; }
        public string ListDescription { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<ListItems> ListItems { get; set; }
        public virtual Users Users { get; set; }
    }
}
