//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItems
    {
        public int ListID { get; set; }
        public string ItemDescription { get; set; }
        public int ListItemID { get; set; }
    
        public virtual Lists Lists { get; set; }
    }
}
